name: Downloads Tracker

on: pull_request
# on: 
#  schedule:
#    - cron:  '0 4 * * *'

jobs:
  Tracker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Get current date
        run: |
          echo "DATE=$('%d-%m-%Y')" >> $GITHUB_ENV
        
      - name: cURL GitHub
        env:
          URL: https://api.github.com/repos/datreeio/datree/releases
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl $URL -o ${{ env.DATE }}.json

      - name: Commit report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "downloads-tracker"
          git config --global user.email "github-actions@datree.io"
          git add .
          git remote set-url origin https://datreeio/cli-downloads-tracker.git
          git commit -a -m "Automated tracking for ${{ env.DATE }}"
          git push origin master --force
