name: Downloads Tracker

on: pull_request
# on: 
#  schedule:
#    - cron:  '0 4 * * *'

jobs:
  Tracker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Get current date
        run: |
          echo "DATE=$(date '+%d-%m-%Y')" >> $GITHUB_ENV
        
      - name: cURL GitHub
        env:
          URL: https://api.github.com/repos/datreeio/datree/releases
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl $URL -o ${{ env.DATE }}.json

      - name: Commit report
        run: |
          git config --global user.name "downloads-tracker"
          git config --global user.email "github-actions@datree.io"
          git add .
          git commit -a -m "Automated tracking for ${{ env.DATE }}"
          git push
#         git remote set-url origin https://datreeio/cli-downloads-tracker.git
#         git push origin main --force
          
#       - name: Push changes
#         uses: ad-m/github-push-action@master
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           branch: main
